---
# tasks file for httpd
- name: "Apache package installation"
  yum:
    name: "httpd"
    state: "present"
- name: "Start apache service"
  service:
    name: "httpd"
    state: "started"
    enabled: yes
